pool:
  vmImage: "ubuntu-latest"

variables:
  imageName: spring-demo

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: "complete/pom.xml"
      options: "-Dspring.profiles.active=dev"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.8"
      jdkArchitectureOption: "x64"
      publishJUnitResults: false
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      goals: "package"
  # - script: |
  #     echo Build docker image
  #     docker build -t $username.azurecr.io/$(imageName):$(Build.BuildNumber) .
  #     echo Login to docker repository
  #     docker login -u $username -p $password $username.azurecr.io
  #     echo Push docker image
  #     docker push $username.azurecr.io/$(imageName):$(Build.BuildNumber)
  #   displayName: "Build and Push Docker Image"
  #   env:
  #     username: $(acrUsername)
  #     password: $(acrPassword)
