pool:
  vmImage: "ubuntu-latest"

variables:
  imageName: spring-demo
  major: 1
  minor: 1
name: $(major).$(minor)$(Rev:.r)

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: "complete/pom.xml"
      options: "versions:set -DnewVersion=$(Build.BuildNumber)"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.8"
      jdkArchitectureOption: "x64"
      publishJUnitResults: false
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      goals: "package"
  - script: |
      echo Build docker image
      docker build -f complete/Dockerfile -t $DOCKER_USERNAME.azurecr.io/$(imageName):$(Build.BuildNumber) complete
      echo Login to docker repository
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_USERNAME.azurecr.io
      echo Push docker image
      docker push $DOCKER_USERNAME.azurecr.io/$(imageName):$(Build.BuildNumber)
    displayName: "Build and Push Docker Image"
    env:
      DOCKER_USERNAME: $(DOCKER_USERNAME)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
  - task: HelmDeploy@0
    displayName: Helm package
    inputs:
      command: package
      version: $(Build.BuildNumber)
      app-version: $(Build.BuildNumber)
      chartPath: helmchart/sping-demo
      destination: $(Build.ArtifactStagingDirectory)
