version: '1.0'
stages:
  - prepare
  - test
  - build and push docker image
  - store
  - deploy
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'diyalab/gs-spring-boot-docker'
    revision: master
    git: github
  run_unit_tests:
    title: Compile/Unit test
    stage: test
    image: 'maven:3.5.2-jdk-8-alpine'
    working_directory: ./complete
    commands:
      - mvn package
  build_app_image:
    title: Building Docker Image
    type: build
    stage: build and push docker image
    image_name: spring-boot-2-sample-app
    working_directory: ./complete
    tag: ${{CF_SHORT_REVISION}}
    dockerfile: Dockerfile
    registry: gcr
  StoreChart:
    title: Storing Helm Chart
    type: helm
    stage: store
    working_directory: ./gs-spring-boot-docker
    arguments:
      action: push
      helm_version: 3.0.2
      chart_name: helmchart/sping-demo
      chart_repo_url: 'cm://h.cfcr.io/siva273/default'
      kube_context: locus@siva
  deploy:
    title: Deploying Helm Chart
    type: helm
    stage: deploy
    working_directory: ./gs-spring-boot-docker
    arguments:
      action: install
      chart_name: helmchart/sping-demo
      release_name: spring-demo
      helm_version: 3.0.2
      kube_context: locus@siva
      skip_cf_stable_helm_repo: true
      custom_values:
        - 'image.tag=${{CF_SHORT_REVISION}}'
        